name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine
        # Install MCP dependency for version check
        pip install mcp>=1.0.0

    - name: Verify version matches tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        PACKAGE_VERSION=$(python -c "from src import __version__; print(__version__)")
        echo "Tag version: $TAG_VERSION"
        echo "Package version: $PACKAGE_VERSION"
        if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
          echo "Version mismatch! Tag: $TAG_VERSION, Package: $PACKAGE_VERSION"
          exit 1
        fi

    - name: Build package
      run: |
        python -m build

    - name: Verify package
      run: |
        twine check dist/*

    - name: Extract tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: ${{ steps.tag.outputs.tag }}
        body: |
          # Codex Bridge ${{ steps.tag.outputs.tag }}
          
          Lightweight MCP server bridging Claude Code to OpenAI's Codex AI through the official CLI.
          
          ## 🚀 Installation
          
          **PyPI Installation:**
          ```bash
          pip install codex-bridge==${{ steps.tag.outputs.tag }}
          ```
          
          **Claude Code Integration:**
          ```bash
          claude mcp add codex-bridge -s user -- uvx codex-bridge
          ```
          
          ## 📋 What's Changed
          
          See [CHANGELOG.md](https://github.com/shelakh/codex-bridge/blob/main/CHANGELOG.md) for detailed changes.
          
          ## 📖 Documentation
          
          - **Full Documentation:** [README.md](https://github.com/shelakh/codex-bridge/blob/main/README.md)
          - **Contributing:** [CONTRIBUTING.md](https://github.com/shelakh/codex-bridge/blob/main/CONTRIBUTING.md)  
          - **Testing:** [tests/README.md](https://github.com/shelakh/codex-bridge/blob/main/tests/README.md)
          
          ## ✅ Verification
          
          All tests passing with comprehensive functionality verification included.
        draft: false
        prerelease: false
        files: |
          dist/*.whl
          dist/*.tar.gz

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}